language: python
python:
- '2.7'
install: pip install -r requirements.txt
script: python -m unittest discover
notifications:
  slack:
    secure: R9dz+8YcDjuP272D7/FUPn/f7QqENuUHz1s9UrLj9J+4PiHwGN7gIkiTYeXDmKJQXebBuZ8/OK+vv/Y7Qs1zYTcXxyi6p4LGFeTlMYhBszyHTOVPMUDHpC0ocAn9l2HXuwlI2Qy9VTVKnL2cBL0tRtpkLg3X62RwXb67gfxfGipm6dEUYgbLNIcYdMtCx+BwaGApDfa78aKdAEQyew3lh/lF75UA248loHNVobirkYjHI5QlFbSOK91ReshHntjfk7xH6CMBM8VUkbWM4RXlelJ17T9hBnavgVcZEMSTQX//tmbN/Y9NTOXL7hLeXEz8vVQg8F6qkSYKKSmWGvD4WafDOoH2+Qt+e+M8L7dg65gW4hS7Ohin4CPuef/wVKOZARkxiEyagJhq+0X8HIykuun+QhutCoIKNJW8Ecpg1MLb2VI4iAxsAmcylLJF0G8CM73k1RmAbJAPSyUEW+U/4gF0TIk4BAcNMe75orPtdOmcZ0QvyARld7fCSgk/yTMQ58zRzeGkpijngYOAg6lQZ5MJyfK7bXxaXhHgzamL2Zcu0JCcTvBfgnfzCUe44YapBH+ymzvDcYsZ2hAmHv1tzZAjYRHtK1SIXjTiWTPdJb9A9W4u08LoZlxPlhDnzOOwoVkQ7fgJYzdyj2Cs+Jm+M/coNOR2P9hIJ/x5tytHpHM=
